#FROM flyway/flyway
#VOLUME ../../jpts/modules/db-dev/src/main/resources/db/migration:/flyway/sql
#COPY src/main/resources/db/migration/ /flyway/sql/
#ENTRYPOINT flyway -url=jdbc:postgresql://postgres-db:5432/jpts_dev -user=jpos -password=password -connectRetries=60 migrate -X