FROM amazoncorretto:11
ENV JCARD_BIMO_REMOTE_PORT 19000
ENV JPOS_ELK_HOST https://vpc-prepaid-dev-e2nbrpzj5z2n723imfdm3hsboi.us-east-1.es.amazonaws.com
ENV JPOS_ELK_PASS X*464jE7
ENV JPOS_ELK_USER user_app
ENV AWS_XRAY_CONTEXT_MISSING LOG_ERROR
ENV BIMO_HOST localhost
ENV BIMO_PORT 9000
ENV JPTS_DB_HOST postgres-db
ENV JPTS_DB_PORT 5432
ENV JPTS_DB_NAME jpts_dev
ENV JPTS_DB_USER jpos
ENV JPTS_DB_PASS password
ENV JPTS_SERVER_PORT 7777
#USER 1000:1000
WORKDIR etc
RUN yum -y install git
RUN git clone https://github.com/vimartinez/testDockerCompose.git
RUN chmod -R 777 testDockerCompose
CMD ["testDockerCompose/jpts-app/bin/q2"]