
  <participant class="org.jpos.jpts.CreateTranLog" logger="Q2" realm="create-tranlog">
   <property name="queue"        value="JPTS.TXN" />
   <property name="space"        value="tspace:default" />
   <property name="capture-date" value="capture-date" />
   <property name="checkpoint"   value="create-tranlog" />
   <property name="node"         value="JPTS01" />
   <property name="kid"          value="&KID;" />
   <property name="stanspace"    value="je:sequencers:log/sequencers" />
  </participant>

